### ISSUE TITLE
[Feature] adding the ability to provide suffix for events and their names

### ISSUE THREAD

**Issue by mboyle3** [event-driven-dotnet/EventDriven.EventBus.Abstractions#3]
The library currently has the ability to provide prefixes for event names. It would be great to have a suffix solution also.

I would like to see the additional parameter for 'suffix' on all event publish and subscribe methods.

I realize that I could name my event 'name' with a suffix. Having the suffix parameter on methods aligns with the already existing prefix functionality.

**Comment by tonysneed** [comment]
Great idea.
